services:
  udm-memory-controller:
    image: ghcr.io/phillipunzen/unifi_udm_memory_leak_fixer:latest
    container_name: udm-memory-controller
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./ssh:/ssh:ro
    restart: unless-stopped
